// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/webss.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebssClient is the client API for Webss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebssClient interface {
	DeleteFiles(ctx context.Context, in *Files, opts ...grpc.CallOption) (*WEmpty, error)
	SetLifecycle(ctx context.Context, in *Lifecycle, opts ...grpc.CallOption) (*ID, error)
	DelLifecycle(ctx context.Context, in *Lifecycles, opts ...grpc.CallOption) (*WEmpty, error)
	AddTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*WEmpty, error)
	GetUrl(ctx context.Context, in *Sign, opts ...grpc.CallOption) (*SignUrl, error)
	GetUrls(ctx context.Context, in *Signs, opts ...grpc.CallOption) (*SignUrls, error)
}

type webssClient struct {
	cc grpc.ClientConnInterface
}

func NewWebssClient(cc grpc.ClientConnInterface) WebssClient {
	return &webssClient{cc}
}

func (c *webssClient) DeleteFiles(ctx context.Context, in *Files, opts ...grpc.CallOption) (*WEmpty, error) {
	out := new(WEmpty)
	err := c.cc.Invoke(ctx, "/proto.Webss/DeleteFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webssClient) SetLifecycle(ctx context.Context, in *Lifecycle, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/proto.Webss/SetLifecycle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webssClient) DelLifecycle(ctx context.Context, in *Lifecycles, opts ...grpc.CallOption) (*WEmpty, error) {
	out := new(WEmpty)
	err := c.cc.Invoke(ctx, "/proto.Webss/DelLifecycle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webssClient) AddTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*WEmpty, error) {
	out := new(WEmpty)
	err := c.cc.Invoke(ctx, "/proto.Webss/AddTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webssClient) GetUrl(ctx context.Context, in *Sign, opts ...grpc.CallOption) (*SignUrl, error) {
	out := new(SignUrl)
	err := c.cc.Invoke(ctx, "/proto.Webss/GetUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webssClient) GetUrls(ctx context.Context, in *Signs, opts ...grpc.CallOption) (*SignUrls, error) {
	out := new(SignUrls)
	err := c.cc.Invoke(ctx, "/proto.Webss/GetUrls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebssServer is the server API for Webss service.
// All implementations must embed UnimplementedWebssServer
// for forward compatibility
type WebssServer interface {
	DeleteFiles(context.Context, *Files) (*WEmpty, error)
	SetLifecycle(context.Context, *Lifecycle) (*ID, error)
	DelLifecycle(context.Context, *Lifecycles) (*WEmpty, error)
	AddTag(context.Context, *Tag) (*WEmpty, error)
	GetUrl(context.Context, *Sign) (*SignUrl, error)
	GetUrls(context.Context, *Signs) (*SignUrls, error)
	mustEmbedUnimplementedWebssServer()
}

// UnimplementedWebssServer must be embedded to have forward compatible implementations.
type UnimplementedWebssServer struct {
}

func (UnimplementedWebssServer) DeleteFiles(context.Context, *Files) (*WEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFiles not implemented")
}
func (UnimplementedWebssServer) SetLifecycle(context.Context, *Lifecycle) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLifecycle not implemented")
}
func (UnimplementedWebssServer) DelLifecycle(context.Context, *Lifecycles) (*WEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelLifecycle not implemented")
}
func (UnimplementedWebssServer) AddTag(context.Context, *Tag) (*WEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTag not implemented")
}
func (UnimplementedWebssServer) GetUrl(context.Context, *Sign) (*SignUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedWebssServer) GetUrls(context.Context, *Signs) (*SignUrls, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrls not implemented")
}
func (UnimplementedWebssServer) mustEmbedUnimplementedWebssServer() {}

// UnsafeWebssServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebssServer will
// result in compilation errors.
type UnsafeWebssServer interface {
	mustEmbedUnimplementedWebssServer()
}

func RegisterWebssServer(s grpc.ServiceRegistrar, srv WebssServer) {
	s.RegisterService(&Webss_ServiceDesc, srv)
}

func _Webss_DeleteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Files)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).DeleteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/DeleteFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).DeleteFiles(ctx, req.(*Files))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webss_SetLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lifecycle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).SetLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/SetLifecycle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).SetLifecycle(ctx, req.(*Lifecycle))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webss_DelLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lifecycles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).DelLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/DelLifecycle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).DelLifecycle(ctx, req.(*Lifecycles))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webss_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/AddTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).AddTag(ctx, req.(*Tag))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webss_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/GetUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).GetUrl(ctx, req.(*Sign))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webss_GetUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Signs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebssServer).GetUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Webss/GetUrls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebssServer).GetUrls(ctx, req.(*Signs))
	}
	return interceptor(ctx, in, info, handler)
}

// Webss_ServiceDesc is the grpc.ServiceDesc for Webss service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Webss_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Webss",
	HandlerType: (*WebssServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFiles",
			Handler:    _Webss_DeleteFiles_Handler,
		},
		{
			MethodName: "SetLifecycle",
			Handler:    _Webss_SetLifecycle_Handler,
		},
		{
			MethodName: "DelLifecycle",
			Handler:    _Webss_DelLifecycle_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _Webss_AddTag_Handler,
		},
		{
			MethodName: "GetUrl",
			Handler:    _Webss_GetUrl_Handler,
		},
		{
			MethodName: "GetUrls",
			Handler:    _Webss_GetUrls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/webss.proto",
}
