//*
// ifscgsrv service is deal redis

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/ifscg/ifscg.proto

package ifscg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//*
// EventResponse is return response
type EventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqID   string `protobuf:"bytes,1,opt,name=ReqID,proto3" json:"ReqID,omitempty"`     /// ReqID is request id
	EvtName string `protobuf:"bytes,2,opt,name=EvtName,proto3" json:"EvtName,omitempty"` /// EvtName is event name
	Data    string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`       /// Data is request data
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ifscg_ifscg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ifscg_ifscg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_ifscg_ifscg_proto_rawDescGZIP(), []int{0}
}

func (x *EventResponse) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

func (x *EventResponse) GetEvtName() string {
	if x != nil {
		return x.EvtName
	}
	return ""
}

func (x *EventResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

//*
// EmptyRequest is a empty request
type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ifscg_ifscg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ifscg_ifscg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ifscg_ifscg_proto_rawDescGZIP(), []int{1}
}

//*
// Message is pub message
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvtName string `protobuf:"bytes,1,opt,name=EvtName,proto3" json:"EvtName,omitempty"` /// EvtName is event name
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ifscg_ifscg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ifscg_ifscg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ifscg_ifscg_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetEvtName() string {
	if x != nil {
		return x.EvtName
	}
	return ""
}

//*
// Response is return response status
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"` /// Status is http status code
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ifscg_ifscg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ifscg_ifscg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_ifscg_ifscg_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_ifscg_ifscg_proto protoreflect.FileDescriptor

var file_proto_ifscg_ifscg_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x66, 0x73, 0x63, 0x67, 0x2f, 0x69, 0x66,
	0x73, 0x63, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x66, 0x73, 0x63, 0x67,
	0x22, 0x53, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x76, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x7b,
	0x0a, 0x08, 0x49, 0x66, 0x73, 0x63, 0x67, 0x73, 0x72, 0x76, 0x12, 0x38, 0x0a, 0x09, 0x53, 0x65,
	0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x2e, 0x69, 0x66, 0x73, 0x63, 0x67, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x69,
	0x66, 0x73, 0x63, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x46,
	0x69, 0x74, 0x12, 0x14, 0x2e, 0x69, 0x66, 0x73, 0x63, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x0f, 0x2e, 0x69, 0x66, 0x73, 0x63, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_ifscg_ifscg_proto_rawDescOnce sync.Once
	file_proto_ifscg_ifscg_proto_rawDescData = file_proto_ifscg_ifscg_proto_rawDesc
)

func file_proto_ifscg_ifscg_proto_rawDescGZIP() []byte {
	file_proto_ifscg_ifscg_proto_rawDescOnce.Do(func() {
		file_proto_ifscg_ifscg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ifscg_ifscg_proto_rawDescData)
	})
	return file_proto_ifscg_ifscg_proto_rawDescData
}

var file_proto_ifscg_ifscg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ifscg_ifscg_proto_goTypes = []interface{}{
	(*EventResponse)(nil), // 0: ifscg.EventResponse
	(*EmptyRequest)(nil),  // 1: ifscg.EmptyRequest
	(*Message)(nil),       // 2: ifscg.Message
	(*Response)(nil),      // 3: ifscg.Response
}
var file_proto_ifscg_ifscg_proto_depIdxs = []int32{
	1, // 0: ifscg.Ifscgsrv.SendEvent:input_type -> ifscg.EmptyRequest
	0, // 1: ifscg.Ifscgsrv.RecRespFit:input_type -> ifscg.EventResponse
	0, // 2: ifscg.Ifscgsrv.SendEvent:output_type -> ifscg.EventResponse
	3, // 3: ifscg.Ifscgsrv.RecRespFit:output_type -> ifscg.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ifscg_ifscg_proto_init() }
func file_proto_ifscg_ifscg_proto_init() {
	if File_proto_ifscg_ifscg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ifscg_ifscg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ifscg_ifscg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ifscg_ifscg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ifscg_ifscg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ifscg_ifscg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ifscg_ifscg_proto_goTypes,
		DependencyIndexes: file_proto_ifscg_ifscg_proto_depIdxs,
		MessageInfos:      file_proto_ifscg_ifscg_proto_msgTypes,
	}.Build()
	File_proto_ifscg_ifscg_proto = out.File
	file_proto_ifscg_ifscg_proto_rawDesc = nil
	file_proto_ifscg_ifscg_proto_goTypes = nil
	file_proto_ifscg_ifscg_proto_depIdxs = nil
}
