// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/vcall/vcall.proto

package vcall

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Logo  string `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Corp  string `protobuf:"bytes,3,opt,name=corp,proto3" json:"corp,omitempty"`
	Dep   string `protobuf:"bytes,4,opt,name=dep,proto3" json:"dep,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AgentInfo) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *AgentInfo) GetCorp() string {
	if x != nil {
		return x.Corp
	}
	return ""
}

func (x *AgentInfo) GetDep() string {
	if x != nil {
		return x.Dep
	}
	return ""
}

type UUIDPhone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *UUIDPhone) Reset() {
	*x = UUIDPhone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUIDPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDPhone) ProtoMessage() {}

func (x *UUIDPhone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDPhone.ProtoReflect.Descriptor instead.
func (*UUIDPhone) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{1}
}

func (x *UUIDPhone) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UUIDPhone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Exist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *Exist) Reset() {
	*x = Exist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exist) ProtoMessage() {}

func (x *Exist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exist.ProtoReflect.Descriptor instead.
func (*Exist) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{2}
}

func (x *Exist) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type OwnerPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Page  int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *OwnerPage) Reset() {
	*x = OwnerPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerPage) ProtoMessage() {}

func (x *OwnerPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerPage.ProtoReflect.Descriptor instead.
func (*OwnerPage) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{3}
}

func (x *OwnerPage) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OwnerPage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type AgentProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logo        string `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	Corporation string `protobuf:"bytes,2,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Department  string `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Phone       string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Remained    int64  `protobuf:"varint,5,opt,name=remained,proto3" json:"remained,omitempty"`
}

func (x *AgentProfile) Reset() {
	*x = AgentProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProfile) ProtoMessage() {}

func (x *AgentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProfile.ProtoReflect.Descriptor instead.
func (*AgentProfile) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{4}
}

func (x *AgentProfile) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *AgentProfile) GetCorporation() string {
	if x != nil {
		return x.Corporation
	}
	return ""
}

func (x *AgentProfile) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *AgentProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AgentProfile) GetRemained() int64 {
	if x != nil {
		return x.Remained
	}
	return 0
}

type AgentProfiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*AgentProfile `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
}

func (x *AgentProfiles) Reset() {
	*x = AgentProfiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProfiles) ProtoMessage() {}

func (x *AgentProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProfiles.ProtoReflect.Descriptor instead.
func (*AgentProfiles) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{5}
}

func (x *AgentProfiles) GetAgents() []*AgentProfile {
	if x != nil {
		return x.Agents
	}
	return nil
}

type PhoneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *PhoneReq) Reset() {
	*x = PhoneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneReq) ProtoMessage() {}

func (x *PhoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneReq.ProtoReflect.Descriptor instead.
func (*PhoneReq) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{6}
}

func (x *PhoneReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type PhoneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PhoneResp) Reset() {
	*x = PhoneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneResp) ProtoMessage() {}

func (x *PhoneResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneResp.ProtoReflect.Descriptor instead.
func (*PhoneResp) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{7}
}

func (x *PhoneResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone    string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Remained string `protobuf:"bytes,2,opt,name=remained,proto3" json:"remained,omitempty"`
}

func (x *TradeReq) Reset() {
	*x = TradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeReq) ProtoMessage() {}

func (x *TradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeReq.ProtoReflect.Descriptor instead.
func (*TradeReq) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{8}
}

func (x *TradeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TradeReq) GetRemained() string {
	if x != nil {
		return x.Remained
	}
	return ""
}

type StatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vcall_vcall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vcall_vcall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_proto_vcall_vcall_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_vcall_vcall_proto protoreflect.FileDescriptor

var file_proto_vcall_vcall_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x76, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x63, 0x61, 0x6c, 0x6c,
	0x22, 0x5b, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x72, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x72, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x70, 0x22, 0x35, 0x0a,
	0x09, 0x55, 0x55, 0x49, 0x44, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x6f, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x65, 0x64, 0x22, 0x3c, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x20, 0x0a, 0x08, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x23, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xd3, 0x01, 0x0a,
	0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x10, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x10, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e,
	0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x07, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x12, 0x10, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x1a, 0x0c, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x32, 0x39, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x76, 0x63, 0x61, 0x6c,
	0x6c, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x3c, 0x0a,
	0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x0f, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x76, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_vcall_vcall_proto_rawDescOnce sync.Once
	file_proto_vcall_vcall_proto_rawDescData = file_proto_vcall_vcall_proto_rawDesc
)

func file_proto_vcall_vcall_proto_rawDescGZIP() []byte {
	file_proto_vcall_vcall_proto_rawDescOnce.Do(func() {
		file_proto_vcall_vcall_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vcall_vcall_proto_rawDescData)
	})
	return file_proto_vcall_vcall_proto_rawDescData
}

var file_proto_vcall_vcall_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_vcall_vcall_proto_goTypes = []interface{}{
	(*AgentInfo)(nil),     // 0: vcall.AgentInfo
	(*UUIDPhone)(nil),     // 1: vcall.UUIDPhone
	(*Exist)(nil),         // 2: vcall.Exist
	(*OwnerPage)(nil),     // 3: vcall.OwnerPage
	(*AgentProfile)(nil),  // 4: vcall.AgentProfile
	(*AgentProfiles)(nil), // 5: vcall.AgentProfiles
	(*PhoneReq)(nil),      // 6: vcall.PhoneReq
	(*PhoneResp)(nil),     // 7: vcall.PhoneResp
	(*TradeReq)(nil),      // 8: vcall.TradeReq
	(*StatusResp)(nil),    // 9: vcall.StatusResp
}
var file_proto_vcall_vcall_proto_depIdxs = []int32{
	4, // 0: vcall.AgentProfiles.agents:type_name -> vcall.AgentProfile
	0, // 1: vcall.Agent.Registry:input_type -> vcall.AgentInfo
	3, // 2: vcall.Agent.GetAgents:input_type -> vcall.OwnerPage
	6, // 3: vcall.Agent.GetProfile:input_type -> vcall.PhoneReq
	1, // 4: vcall.Agent.IsExist:input_type -> vcall.UUIDPhone
	6, // 5: vcall.User.CheckPhone:input_type -> vcall.PhoneReq
	8, // 6: vcall.Trade.SetRemained:input_type -> vcall.TradeReq
	7, // 7: vcall.Agent.Registry:output_type -> vcall.PhoneResp
	5, // 8: vcall.Agent.GetAgents:output_type -> vcall.AgentProfiles
	4, // 9: vcall.Agent.GetProfile:output_type -> vcall.AgentProfile
	2, // 10: vcall.Agent.IsExist:output_type -> vcall.Exist
	7, // 11: vcall.User.CheckPhone:output_type -> vcall.PhoneResp
	9, // 12: vcall.Trade.SetRemained:output_type -> vcall.StatusResp
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vcall_vcall_proto_init() }
func file_proto_vcall_vcall_proto_init() {
	if File_proto_vcall_vcall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vcall_vcall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUIDPhone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentProfiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vcall_vcall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vcall_vcall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_vcall_vcall_proto_goTypes,
		DependencyIndexes: file_proto_vcall_vcall_proto_depIdxs,
		MessageInfos:      file_proto_vcall_vcall_proto_msgTypes,
	}.Build()
	File_proto_vcall_vcall_proto = out.File
	file_proto_vcall_vcall_proto_rawDesc = nil
	file_proto_vcall_vcall_proto_goTypes = nil
	file_proto_vcall_vcall_proto_depIdxs = nil
}
