// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/webss.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WEmpty) Reset() {
	*x = WEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WEmpty) ProtoMessage() {}

func (x *WEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WEmpty.ProtoReflect.Descriptor instead.
func (*WEmpty) Descriptor() ([]byte, []int) {
	return file_proto_webss_proto_rawDescGZIP(), []int{0}
}

type DelFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Files  []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *DelFiles) Reset() {
	*x = DelFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFiles) ProtoMessage() {}

func (x *DelFiles) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFiles.ProtoReflect.Descriptor instead.
func (*DelFiles) Descriptor() ([]byte, []int) {
	return file_proto_webss_proto_rawDescGZIP(), []int{1}
}

func (x *DelFiles) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DelFiles) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type DeleteLifeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lifecycleid []string `protobuf:"bytes,1,rep,name=lifecycleid,proto3" json:"lifecycleid,omitempty"`
	Bucket      string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *DeleteLifeConfig) Reset() {
	*x = DeleteLifeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLifeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLifeConfig) ProtoMessage() {}

func (x *DeleteLifeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLifeConfig.ProtoReflect.Descriptor instead.
func (*DeleteLifeConfig) Descriptor() ([]byte, []int) {
	return file_proto_webss_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLifeConfig) GetLifecycleid() []string {
	if x != nil {
		return x.Lifecycleid
	}
	return nil
}

func (x *DeleteLifeConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

var File_proto_webss_proto protoreflect.FileDescriptor

var file_proto_webss_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x08, 0x0a, 0x06, 0x57, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x38, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x4c,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x32, 0x6e, 0x0a, 0x05,
	0x57, 0x65, 0x62, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_webss_proto_rawDescOnce sync.Once
	file_proto_webss_proto_rawDescData = file_proto_webss_proto_rawDesc
)

func file_proto_webss_proto_rawDescGZIP() []byte {
	file_proto_webss_proto_rawDescOnce.Do(func() {
		file_proto_webss_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_webss_proto_rawDescData)
	})
	return file_proto_webss_proto_rawDescData
}

var file_proto_webss_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_webss_proto_goTypes = []interface{}{
	(*WEmpty)(nil),           // 0: proto.WEmpty
	(*DelFiles)(nil),         // 1: proto.DelFiles
	(*DeleteLifeConfig)(nil), // 2: proto.DeleteLifeConfig
}
var file_proto_webss_proto_depIdxs = []int32{
	1, // 0: proto.Webss.DeleteFiles:input_type -> proto.DelFiles
	2, // 1: proto.Webss.DeleteConfig:input_type -> proto.DeleteLifeConfig
	0, // 2: proto.Webss.DeleteFiles:output_type -> proto.WEmpty
	0, // 3: proto.Webss.DeleteConfig:output_type -> proto.WEmpty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_webss_proto_init() }
func file_proto_webss_proto_init() {
	if File_proto_webss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_webss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLifeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_webss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_webss_proto_goTypes,
		DependencyIndexes: file_proto_webss_proto_depIdxs,
		MessageInfos:      file_proto_webss_proto_msgTypes,
	}.Build()
	File_proto_webss_proto = out.File
	file_proto_webss_proto_rawDesc = nil
	file_proto_webss_proto_goTypes = nil
	file_proto_webss_proto_depIdxs = nil
}
