// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/wgchat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid         string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname     string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Headurl      string `protobuf:"bytes,3,opt,name=headurl,proto3" json:"headurl,omitempty"`
	Staffcompany string `protobuf:"bytes,4,opt,name=staffcompany,proto3" json:"staffcompany,omitempty"`
	Client       string `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *StaffAddReq) Reset() {
	*x = StaffAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffAddReq) ProtoMessage() {}

func (x *StaffAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffAddReq.ProtoReflect.Descriptor instead.
func (*StaffAddReq) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{0}
}

func (x *StaffAddReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StaffAddReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *StaffAddReq) GetHeadurl() string {
	if x != nil {
		return x.Headurl
	}
	return ""
}

func (x *StaffAddReq) GetStaffcompany() string {
	if x != nil {
		return x.Staffcompany
	}
	return ""
}

func (x *StaffAddReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type StaffOneStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Company string `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Client  string `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Status  bool   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StaffOneStatus) Reset() {
	*x = StaffOneStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffOneStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffOneStatus) ProtoMessage() {}

func (x *StaffOneStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffOneStatus.ProtoReflect.Descriptor instead.
func (*StaffOneStatus) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{1}
}

func (x *StaffOneStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StaffOneStatus) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *StaffOneStatus) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *StaffOneStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type StaffComStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company string `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Client  string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Status  bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StaffComStatus) Reset() {
	*x = StaffComStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffComStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffComStatus) ProtoMessage() {}

func (x *StaffComStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffComStatus.ProtoReflect.Descriptor instead.
func (*StaffComStatus) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{2}
}

func (x *StaffComStatus) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *StaffComStatus) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *StaffComStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type StaffDelOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Company string `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Client  string `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *StaffDelOne) Reset() {
	*x = StaffDelOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffDelOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDelOne) ProtoMessage() {}

func (x *StaffDelOne) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDelOne.ProtoReflect.Descriptor instead.
func (*StaffDelOne) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{3}
}

func (x *StaffDelOne) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StaffDelOne) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *StaffDelOne) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type StaffDelAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company string `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Client  string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *StaffDelAll) Reset() {
	*x = StaffDelAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffDelAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDelAll) ProtoMessage() {}

func (x *StaffDelAll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDelAll.ProtoReflect.Descriptor instead.
func (*StaffDelAll) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{4}
}

func (x *StaffDelAll) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *StaffDelAll) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type WgchatEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WgchatEmpty) Reset() {
	*x = WgchatEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wgchat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WgchatEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgchatEmpty) ProtoMessage() {}

func (x *WgchatEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wgchat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgchatEmpty.ProtoReflect.Descriptor instead.
func (*WgchatEmpty) Descriptor() ([]byte, []int) {
	return file_proto_wgchat_proto_rawDescGZIP(), []int{5}
}

var File_proto_wgchat_proto protoreflect.FileDescriptor

var file_proto_wgchat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x67, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x0b,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x75, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x66, 0x66, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0x6e, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x5a, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x53, 0x0a,
	0x0b, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x6c, 0x41, 0x6c,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x57, 0x67, 0x63, 0x68, 0x61, 0x74, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0x94, 0x02, 0x0a, 0x06, 0x77, 0x67, 0x63, 0x68, 0x61, 0x74, 0x12, 0x32, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x67, 0x63, 0x68, 0x61, 0x74, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x70, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4f, 0x6e,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x67, 0x63, 0x68, 0x61, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0b, 0x55,
	0x70, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x67, 0x63, 0x68, 0x61, 0x74,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x12,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44, 0x65, 0x6c,
	0x4f, 0x6e, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x67, 0x63, 0x68,
	0x61, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x41, 0x6c,
	0x6c, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x44,
	0x65, 0x6c, 0x41, 0x6c, 0x6c, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x67,
	0x63, 0x68, 0x61, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wgchat_proto_rawDescOnce sync.Once
	file_proto_wgchat_proto_rawDescData = file_proto_wgchat_proto_rawDesc
)

func file_proto_wgchat_proto_rawDescGZIP() []byte {
	file_proto_wgchat_proto_rawDescOnce.Do(func() {
		file_proto_wgchat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wgchat_proto_rawDescData)
	})
	return file_proto_wgchat_proto_rawDescData
}

var file_proto_wgchat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_wgchat_proto_goTypes = []interface{}{
	(*StaffAddReq)(nil),    // 0: proto.StaffAddReq
	(*StaffOneStatus)(nil), // 1: proto.StaffOneStatus
	(*StaffComStatus)(nil), // 2: proto.StaffComStatus
	(*StaffDelOne)(nil),    // 3: proto.StaffDelOne
	(*StaffDelAll)(nil),    // 4: proto.StaffDelAll
	(*WgchatEmpty)(nil),    // 5: proto.WgchatEmpty
}
var file_proto_wgchat_proto_depIdxs = []int32{
	0, // 0: proto.wgchat.AddStaff:input_type -> proto.StaffAddReq
	1, // 1: proto.wgchat.UpOneStatus:input_type -> proto.StaffOneStatus
	2, // 2: proto.wgchat.UpAllStatus:input_type -> proto.StaffComStatus
	3, // 3: proto.wgchat.DelOne:input_type -> proto.StaffDelOne
	4, // 4: proto.wgchat.DelAll:input_type -> proto.StaffDelAll
	5, // 5: proto.wgchat.AddStaff:output_type -> proto.WgchatEmpty
	5, // 6: proto.wgchat.UpOneStatus:output_type -> proto.WgchatEmpty
	5, // 7: proto.wgchat.UpAllStatus:output_type -> proto.WgchatEmpty
	5, // 8: proto.wgchat.DelOne:output_type -> proto.WgchatEmpty
	5, // 9: proto.wgchat.DelAll:output_type -> proto.WgchatEmpty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wgchat_proto_init() }
func file_proto_wgchat_proto_init() {
	if File_proto_wgchat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wgchat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wgchat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffOneStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wgchat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffComStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wgchat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffDelOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wgchat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffDelAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wgchat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WgchatEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wgchat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wgchat_proto_goTypes,
		DependencyIndexes: file_proto_wgchat_proto_depIdxs,
		MessageInfos:      file_proto_wgchat_proto_msgTypes,
	}.Build()
	File_proto_wgchat_proto = out.File
	file_proto_wgchat_proto_rawDesc = nil
	file_proto_wgchat_proto_goTypes = nil
	file_proto_wgchat_proto_depIdxs = nil
}
