// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/accservice/accservice.proto

package accservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *Phone) Reset() {
	*x = Phone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{3}
}

func (x *Phone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{4}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ViaCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ViaCode) Reset() {
	*x = ViaCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViaCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViaCode) ProtoMessage() {}

func (x *ViaCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViaCode.ProtoReflect.Descriptor instead.
func (*ViaCode) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{5}
}

func (x *ViaCode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ViaCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AccPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Pwd string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *AccPwd) Reset() {
	*x = AccPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccPwd) ProtoMessage() {}

func (x *AccPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccPwd.ProtoReflect.Descriptor instead.
func (*AccPwd) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{6}
}

func (x *AccPwd) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AccPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type ViaPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Pwd   string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *ViaPwd) Reset() {
	*x = ViaPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViaPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViaPwd) ProtoMessage() {}

func (x *ViaPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViaPwd.ProtoReflect.Descriptor instead.
func (*ViaPwd) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{7}
}

func (x *ViaPwd) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ViaPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type ViaReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Pwd  string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *ViaReg) Reset() {
	*x = ViaReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViaReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViaReg) ProtoMessage() {}

func (x *ViaReg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViaReg.ProtoReflect.Descriptor instead.
func (*ViaReg) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{8}
}

func (x *ViaReg) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ViaReg) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ViaReg) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type TokenPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid  string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pwd   string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *TokenPwd) Reset() {
	*x = TokenPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPwd) ProtoMessage() {}

func (x *TokenPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPwd.ProtoReflect.Descriptor instead.
func (*TokenPwd) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{9}
}

func (x *TokenPwd) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenPwd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TokenPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type TokenPhone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *TokenPhone) Reset() {
	*x = TokenPhone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPhone) ProtoMessage() {}

func (x *TokenPhone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPhone.ProtoReflect.Descriptor instead.
func (*TokenPhone) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{10}
}

func (x *TokenPhone) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenPhone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type TokenEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *TokenEmail) Reset() {
	*x = TokenEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEmail) ProtoMessage() {}

func (x *TokenEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEmail.ProtoReflect.Descriptor instead.
func (*TokenEmail) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{11}
}

func (x *TokenEmail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TokenCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid  string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code  string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *TokenCode) Reset() {
	*x = TokenCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCode) ProtoMessage() {}

func (x *TokenCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCode.ProtoReflect.Descriptor instead.
func (*TokenCode) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{12}
}

func (x *TokenCode) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenCode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TokenCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PhoneEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *PhoneEmail) Reset() {
	*x = PhoneEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneEmail) ProtoMessage() {}

func (x *PhoneEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneEmail.ProtoReflect.Descriptor instead.
func (*PhoneEmail) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{13}
}

func (x *PhoneEmail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Profiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role        string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Nickname    string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Heardurl    string `protobuf:"bytes,4,opt,name=heardurl,proto3" json:"heardurl,omitempty"`
	Country     string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Provice     string `protobuf:"bytes,6,opt,name=provice,proto3" json:"provice,omitempty"`
	City        string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Corporation string `protobuf:"bytes,8,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Department  string `protobuf:"bytes,9,opt,name=department,proto3" json:"department,omitempty"`
	Latest      string `protobuf:"bytes,10,opt,name=latest,proto3" json:"latest,omitempty"`
	Sex         int64  `protobuf:"varint,11,opt,name=sex,proto3" json:"sex,omitempty"`
	Height      int64  `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`
	Weight      int64  `protobuf:"varint,13,opt,name=weight,proto3" json:"weight,omitempty"`
	Birthday    int64  `protobuf:"varint,14,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (x *Profiles) Reset() {
	*x = Profiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profiles) ProtoMessage() {}

func (x *Profiles) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profiles.ProtoReflect.Descriptor instead.
func (*Profiles) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{14}
}

func (x *Profiles) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Profiles) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Profiles) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profiles) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

func (x *Profiles) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Profiles) GetProvice() string {
	if x != nil {
		return x.Provice
	}
	return ""
}

func (x *Profiles) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Profiles) GetCorporation() string {
	if x != nil {
		return x.Corporation
	}
	return ""
}

func (x *Profiles) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Profiles) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

func (x *Profiles) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Profiles) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Profiles) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Profiles) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

type ProfSumm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role     string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Heardurl string `protobuf:"bytes,4,opt,name=heardurl,proto3" json:"heardurl,omitempty"`
}

func (x *ProfSumm) Reset() {
	*x = ProfSumm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfSumm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfSumm) ProtoMessage() {}

func (x *ProfSumm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfSumm.ProtoReflect.Descriptor instead.
func (*ProfSumm) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{15}
}

func (x *ProfSumm) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProfSumm) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProfSumm) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfSumm) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type ProfInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Heardurl string `protobuf:"bytes,3,opt,name=heardurl,proto3" json:"heardurl,omitempty"`
}

func (x *ProfInfo) Reset() {
	*x = ProfInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfInfo) ProtoMessage() {}

func (x *ProfInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfInfo.ProtoReflect.Descriptor instead.
func (*ProfInfo) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{16}
}

func (x *ProfInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProfInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfInfo) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type ProfInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profinfo []*ProfInfo `protobuf:"bytes,1,rep,name=profinfo,proto3" json:"profinfo,omitempty"`
}

func (x *ProfInfos) Reset() {
	*x = ProfInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfInfos) ProtoMessage() {}

func (x *ProfInfos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfInfos.ProtoReflect.Descriptor instead.
func (*ProfInfos) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{17}
}

func (x *ProfInfos) GetProfinfo() []*ProfInfo {
	if x != nil {
		return x.Profinfo
	}
	return nil
}

type TokeProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role        string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Nickname    string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Country     string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Provice     string `protobuf:"bytes,5,opt,name=provice,proto3" json:"provice,omitempty"`
	City        string `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Corporation string `protobuf:"bytes,7,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Department  string `protobuf:"bytes,8,opt,name=department,proto3" json:"department,omitempty"`
	Sex         int64  `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	Height      int64  `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	Weight      int64  `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Birthday    int64  `protobuf:"varint,12,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (x *TokeProfile) Reset() {
	*x = TokeProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokeProfile) ProtoMessage() {}

func (x *TokeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokeProfile.ProtoReflect.Descriptor instead.
func (*TokeProfile) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{18}
}

func (x *TokeProfile) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokeProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TokeProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TokeProfile) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *TokeProfile) GetProvice() string {
	if x != nil {
		return x.Provice
	}
	return ""
}

func (x *TokeProfile) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *TokeProfile) GetCorporation() string {
	if x != nil {
		return x.Corporation
	}
	return ""
}

func (x *TokeProfile) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *TokeProfile) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *TokeProfile) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TokeProfile) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *TokeProfile) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

type TokeRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role  string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Uuid  string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *TokeRole) Reset() {
	*x = TokeRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokeRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokeRole) ProtoMessage() {}

func (x *TokeRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokeRole.ProtoReflect.Descriptor instead.
func (*TokeRole) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{19}
}

func (x *TokeRole) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokeRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TokeRole) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type TokenSigInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Label   string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Tovalue int64  `protobuf:"varint,3,opt,name=tovalue,proto3" json:"tovalue,omitempty"`
}

func (x *TokenSigInt) Reset() {
	*x = TokenSigInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenSigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSigInt) ProtoMessage() {}

func (x *TokenSigInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSigInt.ProtoReflect.Descriptor instead.
func (*TokenSigInt) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{20}
}

func (x *TokenSigInt) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenSigInt) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TokenSigInt) GetTovalue() int64 {
	if x != nil {
		return x.Tovalue
	}
	return 0
}

type TokenSigStr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Label   string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Tovalue string `protobuf:"bytes,3,opt,name=tovalue,proto3" json:"tovalue,omitempty"`
}

func (x *TokenSigStr) Reset() {
	*x = TokenSigStr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenSigStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSigStr) ProtoMessage() {}

func (x *TokenSigStr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSigStr.ProtoReflect.Descriptor instead.
func (*TokenSigStr) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{21}
}

func (x *TokenSigStr) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenSigStr) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TokenSigStr) GetTovalue() string {
	if x != nil {
		return x.Tovalue
	}
	return ""
}

type TokenUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Suffix  string `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Rawdata string `protobuf:"bytes,3,opt,name=rawdata,proto3" json:"rawdata,omitempty"`
}

func (x *TokenUpload) Reset() {
	*x = TokenUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUpload) ProtoMessage() {}

func (x *TokenUpload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUpload.ProtoReflect.Descriptor instead.
func (*TokenUpload) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{22}
}

func (x *TokenUpload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenUpload) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *TokenUpload) GetRawdata() string {
	if x != nil {
		return x.Rawdata
	}
	return ""
}

type TokePage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role  string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Page  int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *TokePage) Reset() {
	*x = TokePage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokePage) ProtoMessage() {}

func (x *TokePage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokePage.ProtoReflect.Descriptor instead.
func (*TokePage) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{23}
}

func (x *TokePage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokePage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TokePage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{24}
}

func (x *Status) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PublickKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *PublickKey) Reset() {
	*x = PublickKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublickKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublickKey) ProtoMessage() {}

func (x *PublickKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublickKey.ProtoReflect.Descriptor instead.
func (*PublickKey) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{25}
}

func (x *PublickKey) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{26}
}

func (x *Role) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type URLPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urlpath string `protobuf:"bytes,1,opt,name=urlpath,proto3" json:"urlpath,omitempty"`
}

func (x *URLPath) Reset() {
	*x = URLPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPath) ProtoMessage() {}

func (x *URLPath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLPath.ProtoReflect.Descriptor instead.
func (*URLPath) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{27}
}

func (x *URLPath) GetUrlpath() string {
	if x != nil {
		return x.Urlpath
	}
	return ""
}

type Accounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pwd       string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Phone     string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Pubkey    string `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Prikey    string `protobuf:"bytes,6,opt,name=prikey,proto3" json:"prikey,omitempty"`
	Activate  bool   `protobuf:"varint,7,opt,name=activate,proto3" json:"activate,omitempty"`
	Bindphone bool   `protobuf:"varint,8,opt,name=bindphone,proto3" json:"bindphone,omitempty"`
	Bindemail bool   `protobuf:"varint,9,opt,name=bindemail,proto3" json:"bindemail,omitempty"`
}

func (x *Accounts) Reset() {
	*x = Accounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accounts) ProtoMessage() {}

func (x *Accounts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accounts.ProtoReflect.Descriptor instead.
func (*Accounts) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{28}
}

func (x *Accounts) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Accounts) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *Accounts) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Accounts) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Accounts) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Accounts) GetPrikey() string {
	if x != nil {
		return x.Prikey
	}
	return ""
}

func (x *Accounts) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *Accounts) GetBindphone() bool {
	if x != nil {
		return x.Bindphone
	}
	return false
}

func (x *Accounts) GetBindemail() bool {
	if x != nil {
		return x.Bindemail
	}
	return false
}

type AuthCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid     string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Expireat int64  `protobuf:"varint,4,opt,name=expireat,proto3" json:"expireat,omitempty"`
	Code     string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Subinfo  string `protobuf:"bytes,6,opt,name=subinfo,proto3" json:"subinfo,omitempty"`
}

func (x *AuthCode) Reset() {
	*x = AuthCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accservice_accservice_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCode) ProtoMessage() {}

func (x *AuthCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accservice_accservice_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCode.ProtoReflect.Descriptor instead.
func (*AuthCode) Descriptor() ([]byte, []int) {
	return file_proto_accservice_accservice_proto_rawDescGZIP(), []int{29}
}

func (x *AuthCode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthCode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AuthCode) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AuthCode) GetExpireat() int64 {
	if x != nil {
		return x.Expireat
	}
	return 0
}

func (x *AuthCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthCode) GetSubinfo() string {
	if x != nil {
		return x.Subinfo
	}
	return ""
}

var File_proto_accservice_accservice_proto protoreflect.FileDescriptor

var file_proto_accservice_accservice_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x18, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1d, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x31, 0x0a, 0x07, 0x56, 0x69, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x70, 0x77, 0x64, 0x22, 0x30, 0x0a, 0x06, 0x56, 0x69, 0x61, 0x50, 0x77, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x42, 0x0a, 0x06, 0x56, 0x69, 0x61, 0x52, 0x65, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x46, 0x0a, 0x08, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x50, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77,
	0x64, 0x22, 0x38, 0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x49, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x38, 0x0a, 0x0a, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xea, 0x02, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x22, 0x6a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x53,
	0x75, 0x6d, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64,
	0x75, 0x72, 0x6c, 0x22, 0x56, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x22, 0x3d, 0x0a, 0x09, 0x50,
	0x72, 0x6f, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xbb, 0x02, 0x0a, 0x0b, 0x54,
	0x6f, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x70,
	0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x22, 0x48, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x22, 0x53, 0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x49, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x6f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x53, 0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x53, 0x69, 0x67, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x0b,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x77,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x24, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x1a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x22, 0x23, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x72, 0x6c, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75,
	0x72, 0x6c, 0x70, 0x61, 0x74, 0x68, 0x22, 0xe4, 0x01, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x69, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x72, 0x69, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x94, 0x01,
	0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x69, 0x6e, 0x66, 0x6f, 0x32, 0xb0, 0x0a, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x47,
	0x65, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x31,
	0x0a, 0x08, 0x56, 0x69, 0x61, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x10, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x09, 0x56, 0x69, 0x61, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x12, 0x12,
	0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61, 0x50,
	0x77, 0x64, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x6d, 0x73, 0x52, 0x65, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a, 0x10, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a, 0x10, 0x2e, 0x61, 0x63,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0f, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x6d, 0x73, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x10, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x1a, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x1a, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x63,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0c, 0x41, 0x63, 0x74,
	0x42, 0x79, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61, 0x52, 0x65, 0x67, 0x1a, 0x11, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x42, 0x79, 0x53, 0x6d, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x4e, 0x6f, 0x50, 0x77, 0x12, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x11, 0x2e, 0x61, 0x63,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x12, 0x56, 0x69, 0x61, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53,
	0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x11, 0x2e, 0x61, 0x63,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x0f, 0x56, 0x69, 0x61, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x6d, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x56, 0x69, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0e, 0x56, 0x69, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x15, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0e,
	0x41, 0x63, 0x74, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61, 0x52,
	0x65, 0x67, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x14, 0x56, 0x69, 0x61, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x13, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x61,
	0x43, 0x6f, 0x64, 0x65, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x10, 0x56, 0x69, 0x61,
	0x42, 0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x41, 0x63,
	0x63, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0b, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x50, 0x77, 0x64, 0x12, 0x14,
	0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x77, 0x64, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x16, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x00, 0x32, 0xb2, 0x04, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x12,
	0x10, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x1a, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x10, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x17, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14,
	0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x17, 0x2e, 0x61,
	0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53,
	0x69, 0x67, 0x53, 0x74, 0x72, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x17, 0x2e,
	0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x53, 0x69, 0x67, 0x49, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0c,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x61,
	0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x55, 0x52, 0x4c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_accservice_accservice_proto_rawDescOnce sync.Once
	file_proto_accservice_accservice_proto_rawDescData = file_proto_accservice_accservice_proto_rawDesc
)

func file_proto_accservice_accservice_proto_rawDescGZIP() []byte {
	file_proto_accservice_accservice_proto_rawDescOnce.Do(func() {
		file_proto_accservice_accservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_accservice_accservice_proto_rawDescData)
	})
	return file_proto_accservice_accservice_proto_rawDescData
}

var file_proto_accservice_accservice_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_accservice_accservice_proto_goTypes = []interface{}{
	(*UUID)(nil),        // 0: accservice.UUID
	(*Target)(nil),      // 1: accservice.Target
	(*Token)(nil),       // 2: accservice.Token
	(*Phone)(nil),       // 3: accservice.Phone
	(*Email)(nil),       // 4: accservice.Email
	(*ViaCode)(nil),     // 5: accservice.ViaCode
	(*AccPwd)(nil),      // 6: accservice.AccPwd
	(*ViaPwd)(nil),      // 7: accservice.ViaPwd
	(*ViaReg)(nil),      // 8: accservice.ViaReg
	(*TokenPwd)(nil),    // 9: accservice.TokenPwd
	(*TokenPhone)(nil),  // 10: accservice.TokenPhone
	(*TokenEmail)(nil),  // 11: accservice.TokenEmail
	(*TokenCode)(nil),   // 12: accservice.TokenCode
	(*PhoneEmail)(nil),  // 13: accservice.PhoneEmail
	(*Profiles)(nil),    // 14: accservice.Profiles
	(*ProfSumm)(nil),    // 15: accservice.ProfSumm
	(*ProfInfo)(nil),    // 16: accservice.ProfInfo
	(*ProfInfos)(nil),   // 17: accservice.ProfInfos
	(*TokeProfile)(nil), // 18: accservice.TokeProfile
	(*TokeRole)(nil),    // 19: accservice.TokeRole
	(*TokenSigInt)(nil), // 20: accservice.TokenSigInt
	(*TokenSigStr)(nil), // 21: accservice.TokenSigStr
	(*TokenUpload)(nil), // 22: accservice.TokenUpload
	(*TokePage)(nil),    // 23: accservice.TokePage
	(*Status)(nil),      // 24: accservice.Status
	(*PublickKey)(nil),  // 25: accservice.PublickKey
	(*Role)(nil),        // 26: accservice.Role
	(*URLPath)(nil),     // 27: accservice.URLPath
	(*Accounts)(nil),    // 28: accservice.Accounts
	(*AuthCode)(nil),    // 29: accservice.AuthCode
}
var file_proto_accservice_accservice_proto_depIdxs = []int32{
	16, // 0: accservice.ProfInfos.profinfo:type_name -> accservice.ProfInfo
	1,  // 1: accservice.Account.GetPubKey:input_type -> accservice.Target
	0,  // 2: accservice.Account.GenToken:input_type -> accservice.UUID
	2,  // 3: accservice.Account.ViaToken:input_type -> accservice.Token
	7,  // 4: accservice.Account.ViaAccPwd:input_type -> accservice.ViaPwd
	3,  // 5: accservice.Account.SendSmsRegCode:input_type -> accservice.Phone
	3,  // 6: accservice.Account.SendSmsRetrieveCode:input_type -> accservice.Phone
	3,  // 7: accservice.Account.SendSmsLoginCode:input_type -> accservice.Phone
	10, // 8: accservice.Account.SendSmsBindCode:input_type -> accservice.TokenPhone
	4,  // 9: accservice.Account.SendEmailRegCode:input_type -> accservice.Email
	4,  // 10: accservice.Account.SendEmailRetrieveCode:input_type -> accservice.Email
	11, // 11: accservice.Account.SendEmailBindCode:input_type -> accservice.TokenEmail
	8,  // 12: accservice.Account.ActBySmsCode:input_type -> accservice.ViaReg
	5,  // 13: accservice.Account.ActBySmsCodeNoPw:input_type -> accservice.ViaCode
	5,  // 14: accservice.Account.ViaRetrieveSmsCode:input_type -> accservice.ViaCode
	5,  // 15: accservice.Account.ViaLoginSmsCode:input_type -> accservice.ViaCode
	12, // 16: accservice.Account.ViaBindSmsCode:input_type -> accservice.TokenCode
	8,  // 17: accservice.Account.ActByEmailCode:input_type -> accservice.ViaReg
	5,  // 18: accservice.Account.ViaRetrieveEmailCode:input_type -> accservice.ViaCode
	12, // 19: accservice.Account.ViaBindEmailCode:input_type -> accservice.TokenCode
	6,  // 20: accservice.Account.AccLogin:input_type -> accservice.AccPwd
	9,  // 21: accservice.Account.OverridePwd:input_type -> accservice.TokenPwd
	2,  // 22: accservice.Account.GetPhoneEmail:input_type -> accservice.Token
	2,  // 23: accservice.Profile.GetAccProfiles:input_type -> accservice.Token
	0,  // 24: accservice.Profile.GetProfSumm:input_type -> accservice.UUID
	2,  // 25: accservice.Profile.GetAccRole:input_type -> accservice.Token
	23, // 26: accservice.Profile.GetProfsByRole:input_type -> accservice.TokePage
	18, // 27: accservice.Profile.UpdateProfiles:input_type -> accservice.TokeProfile
	19, // 28: accservice.Profile.UpdateRole:input_type -> accservice.TokeRole
	21, // 29: accservice.Profile.UpdateStrField:input_type -> accservice.TokenSigStr
	20, // 30: accservice.Profile.UpdateIntField:input_type -> accservice.TokenSigInt
	22, // 31: accservice.Profile.UploadHeader:input_type -> accservice.TokenUpload
	25, // 32: accservice.Account.GetPubKey:output_type -> accservice.PublickKey
	2,  // 33: accservice.Account.GenToken:output_type -> accservice.Token
	0,  // 34: accservice.Account.ViaToken:output_type -> accservice.UUID
	24, // 35: accservice.Account.ViaAccPwd:output_type -> accservice.Status
	0,  // 36: accservice.Account.SendSmsRegCode:output_type -> accservice.UUID
	0,  // 37: accservice.Account.SendSmsRetrieveCode:output_type -> accservice.UUID
	0,  // 38: accservice.Account.SendSmsLoginCode:output_type -> accservice.UUID
	24, // 39: accservice.Account.SendSmsBindCode:output_type -> accservice.Status
	0,  // 40: accservice.Account.SendEmailRegCode:output_type -> accservice.UUID
	0,  // 41: accservice.Account.SendEmailRetrieveCode:output_type -> accservice.UUID
	24, // 42: accservice.Account.SendEmailBindCode:output_type -> accservice.Status
	2,  // 43: accservice.Account.ActBySmsCode:output_type -> accservice.Token
	2,  // 44: accservice.Account.ActBySmsCodeNoPw:output_type -> accservice.Token
	2,  // 45: accservice.Account.ViaRetrieveSmsCode:output_type -> accservice.Token
	2,  // 46: accservice.Account.ViaLoginSmsCode:output_type -> accservice.Token
	24, // 47: accservice.Account.ViaBindSmsCode:output_type -> accservice.Status
	2,  // 48: accservice.Account.ActByEmailCode:output_type -> accservice.Token
	2,  // 49: accservice.Account.ViaRetrieveEmailCode:output_type -> accservice.Token
	24, // 50: accservice.Account.ViaBindEmailCode:output_type -> accservice.Status
	2,  // 51: accservice.Account.AccLogin:output_type -> accservice.Token
	2,  // 52: accservice.Account.OverridePwd:output_type -> accservice.Token
	13, // 53: accservice.Account.GetPhoneEmail:output_type -> accservice.PhoneEmail
	14, // 54: accservice.Profile.GetAccProfiles:output_type -> accservice.Profiles
	15, // 55: accservice.Profile.GetProfSumm:output_type -> accservice.ProfSumm
	26, // 56: accservice.Profile.GetAccRole:output_type -> accservice.Role
	17, // 57: accservice.Profile.GetProfsByRole:output_type -> accservice.ProfInfos
	24, // 58: accservice.Profile.UpdateProfiles:output_type -> accservice.Status
	24, // 59: accservice.Profile.UpdateRole:output_type -> accservice.Status
	24, // 60: accservice.Profile.UpdateStrField:output_type -> accservice.Status
	24, // 61: accservice.Profile.UpdateIntField:output_type -> accservice.Status
	27, // 62: accservice.Profile.UploadHeader:output_type -> accservice.URLPath
	32, // [32:63] is the sub-list for method output_type
	1,  // [1:32] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_accservice_accservice_proto_init() }
func file_proto_accservice_accservice_proto_init() {
	if File_proto_accservice_accservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_accservice_accservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViaCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViaPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViaReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPhone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfSumm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokeProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokeRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenSigInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenSigStr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokePage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublickKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_accservice_accservice_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_accservice_accservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_accservice_accservice_proto_goTypes,
		DependencyIndexes: file_proto_accservice_accservice_proto_depIdxs,
		MessageInfos:      file_proto_accservice_accservice_proto_msgTypes,
	}.Build()
	File_proto_accservice_accservice_proto = out.File
	file_proto_accservice_accservice_proto_rawDesc = nil
	file_proto_accservice_accservice_proto_goTypes = nil
	file_proto_accservice_accservice_proto_depIdxs = nil
}
