// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/acc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AEmpty) Reset() {
	*x = AEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AEmpty) ProtoMessage() {}

func (x *AEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AEmpty.ProtoReflect.Descriptor instead.
func (*AEmpty) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{0}
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // account request token
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // account unique id
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{2}
}

func (x *UUID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UIDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *UIDS) Reset() {
	*x = UIDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDS) ProtoMessage() {}

func (x *UIDS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDS.ProtoReflect.Descriptor instead.
func (*UIDS) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{3}
}

func (x *UIDS) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type CreateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Createtime int64 `protobuf:"varint,1,opt,name=createtime,proto3" json:"createtime,omitempty"` // createtime of account
}

func (x *CreateTime) Reset() {
	*x = CreateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTime) ProtoMessage() {}

func (x *CreateTime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTime.ProtoReflect.Descriptor instead.
func (*CreateTime) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTime) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

type AccPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"` // account uuid, email or phone
	Pwd string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"` // account login password enripted by RSA + Base64
}

func (x *AccPwd) Reset() {
	*x = AccPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccPwd) ProtoMessage() {}

func (x *AccPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccPwd.ProtoReflect.Descriptor instead.
func (*AccPwd) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{5}
}

func (x *AccPwd) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *AccPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`          // account unique id
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`  // account nickname
	Heardurl string `protobuf:"bytes,3,opt,name=heardurl,proto3" json:"heardurl,omitempty"`  // account heardurl, the value set from wechat avatar or manual update by userself
	Sex      int64  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`           // account sex, 0:none, 1:male, 2:female, 3:neutral
	Birthday string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`  // account birthday, the value set from real-name authentication
	Isverify bool   `protobuf:"varint,6,opt,name=isverify,proto3" json:"isverify,omitempty"` // status to indicate account if pass real-name autnenticated
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{6}
}

func (x *Profile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Profile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profile) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

func (x *Profile) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Profile) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *Profile) GetIsverify() bool {
	if x != nil {
		return x.Isverify
	}
	return false
}

type ProfSumm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // account unique id
	Sex      int64  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`          // account sex, 0:none, 1:male, 2:female, 3:neutral
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // account nickname
	Heardurl string `protobuf:"bytes,4,opt,name=heardurl,proto3" json:"heardurl,omitempty"` // account heardurl, the value set from wechat avatar
}

func (x *ProfSumm) Reset() {
	*x = ProfSumm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfSumm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfSumm) ProtoMessage() {}

func (x *ProfSumm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfSumm.ProtoReflect.Descriptor instead.
func (*ProfSumm) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{7}
}

func (x *ProfSumm) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProfSumm) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *ProfSumm) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfSumm) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type ProfSumms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summs []*ProfSumm `protobuf:"bytes,1,rep,name=summs,proto3" json:"summs,omitempty"`
}

func (x *ProfSumms) Reset() {
	*x = ProfSumms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfSumms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfSumms) ProtoMessage() {}

func (x *ProfSumms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfSumms.ProtoReflect.Descriptor instead.
func (*ProfSumms) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{8}
}

func (x *ProfSumms) GetSumms() []*ProfSumm {
	if x != nil {
		return x.Summs
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Contact string `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"` // account nickname
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`     // account email address
	Phone   string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`     // account email phone
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{9}
}

func (x *Contact) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Contact) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"` // store name frist perfix string
	Province string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"` // store name middle string
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`         // store name the last string
	Email    string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`       // store account email address, set when account generate
	Phone    string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`       // store account phone number, set when account generate
}

func (x *RegStore) Reset() {
	*x = RegStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegStore) ProtoMessage() {}

func (x *RegStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegStore.ProtoReflect.Descriptor instead.
func (*RegStore) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{10}
}

func (x *RegStore) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegStore) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *RegStore) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RegStore) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegStore) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ProfStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logourl  string `protobuf:"bytes,1,opt,name=logourl,proto3" json:"logourl,omitempty"`   // store logo image url from heardurl field value of database
	Unionid  string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"`   // wechat unionid bind with store account
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // store account email address, set when account generate
	Phone    string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`       // store account phone number, set when account generate
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"` // store name frist perfix string
	Province string `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"` // store name middle string
	City     string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`         // store name the last string
	Address  string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`   // store address string
	Uuid     string `protobuf:"bytes,9,opt,name=uuid,proto3" json:"uuid,omitempty"`         // uuid for the profile
}

func (x *ProfStore) Reset() {
	*x = ProfStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfStore) ProtoMessage() {}

func (x *ProfStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfStore.ProtoReflect.Descriptor instead.
func (*ProfStore) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{11}
}

func (x *ProfStore) GetLogourl() string {
	if x != nil {
		return x.Logourl
	}
	return ""
}

func (x *ProfStore) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *ProfStore) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfStore) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ProfStore) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfStore) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ProfStore) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfStore) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProfStore) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ProfStores struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*ProfStore `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *ProfStores) Reset() {
	*x = ProfStores{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfStores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfStores) ProtoMessage() {}

func (x *ProfStores) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfStores.ProtoReflect.Descriptor instead.
func (*ProfStores) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{12}
}

func (x *ProfStores) GetProfiles() []*ProfStore {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type RnStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // account unique id
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // store name frist perfix string
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"` // store name middle string
	City     string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`         // store name the last string
	Address  string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`   // store address string
}

func (x *RnStore) Reset() {
	*x = RnStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RnStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RnStore) ProtoMessage() {}

func (x *RnStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RnStore.ProtoReflect.Descriptor instead.
func (*RnStore) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{13}
}

func (x *RnStore) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RnStore) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RnStore) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *RnStore) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RnStore) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type WxBind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Unionid string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"` // wechat unionid bind with store account
	Pwd     string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`         // account login password enripted by RSA + Base64
}

func (x *WxBind) Reset() {
	*x = WxBind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxBind) ProtoMessage() {}

func (x *WxBind) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxBind.ProtoReflect.Descriptor instead.
func (*WxBind) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{14}
}

func (x *WxBind) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WxBind) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *WxBind) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type Secures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Unionid string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"` // wechat unionid bind with account
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`     // account email address
	Pwd     string `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`         // account login password enripted by RSA + Base64
}

func (x *Secures) Reset() {
	*x = Secures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secures) ProtoMessage() {}

func (x *Secures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secures.ProtoReflect.Descriptor instead.
func (*Secures) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{15}
}

func (x *Secures) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Secures) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *Secures) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Secures) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type Admin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Md5Pwd  string `protobuf:"bytes,2,opt,name=md5pwd,proto3" json:"md5pwd,omitempty"`   // admin account password encode as MD5
	Unionid string `protobuf:"bytes,3,opt,name=unionid,proto3" json:"unionid,omitempty"` // wechat unionid bind with account
}

func (x *Admin) Reset() {
	*x = Admin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{16}
}

func (x *Admin) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Admin) GetMd5Pwd() string {
	if x != nil {
		return x.Md5Pwd
	}
	return ""
}

func (x *Admin) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // verification request account id
	Router string `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"` // verification request API router
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // verification request http method
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{17}
}

func (x *Role) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Role) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *Role) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"` // if account enable access router, ture is allow, false denied
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{18}
}

func (x *Result) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

type UserRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role int64 `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"` // traget role
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{19}
}

func (x *UserRole) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type AddStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // store account email address, set when account generate
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // store name frist perfix string
	Role     int64  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`        // store role, such as store-comp and store-machine
}

func (x *AddStore) Reset() {
	*x = AddStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStore) ProtoMessage() {}

func (x *AddStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStore.ProtoReflect.Descriptor instead.
func (*AddStore) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{20}
}

func (x *AddStore) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddStore) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AddStore) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type RoleProf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // uuid for the profile
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // account email
	Phone    string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`       // account phone
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"` // account nickname
	Heardurl string `protobuf:"bytes,5,opt,name=heardurl,proto3" json:"heardurl,omitempty"` // account heardurl, the value set from wechat avatar
}

func (x *RoleProf) Reset() {
	*x = RoleProf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleProf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleProf) ProtoMessage() {}

func (x *RoleProf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleProf.ProtoReflect.Descriptor instead.
func (*RoleProf) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{21}
}

func (x *RoleProf) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RoleProf) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RoleProf) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RoleProf) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleProf) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type RoleProfs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*RoleProf `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *RoleProfs) Reset() {
	*x = RoleProfs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleProfs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleProfs) ProtoMessage() {}

func (x *RoleProfs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleProfs.ProtoReflect.Descriptor instead.
func (*RoleProfs) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{22}
}

func (x *RoleProfs) GetProfiles() []*RoleProf {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_proto_acc_proto protoreflect.FileDescriptor

var file_proto_acc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x08, 0x0a, 0x06, 0x41, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x1a, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a,
	0x04, 0x55, 0x49, 0x44, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x2c, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x50, 0x77,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x68, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x53,
	0x75, 0x6d, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72,
	0x6c, 0x22, 0x32, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x05, 0x73, 0x75, 0x6d, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x52, 0x05,
	0x73, 0x75, 0x6d, 0x6d, 0x73, 0x22, 0x63, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22,
	0xe5, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x07, 0x52, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a, 0x06, 0x57, 0x78, 0x42,
	0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x70, 0x77, 0x64, 0x22, 0x5f, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x77, 0x64, 0x22, 0x4d, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x64, 0x35, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x64, 0x35, 0x70, 0x77, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22,
	0x1c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x1e, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x50, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22,
	0x82, 0x01, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72,
	0x64, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72,
	0x64, 0x75, 0x72, 0x6c, 0x22, 0x38, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x73, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x32, 0xe0,
	0x06, 0x0a, 0x03, 0x41, 0x63, 0x63, 0x12, 0x27, 0x0a, 0x08, 0x56, 0x69, 0x61, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x12,
	0x25, 0x0a, 0x07, 0x56, 0x69, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x56, 0x69, 0x61, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x27, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75,
	0x6d, 0x6d, 0x73, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x49, 0x44, 0x53,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d,
	0x6d, 0x73, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x2f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x1a,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x75, 0x6d, 0x6d,
	0x73, 0x12, 0x2d, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x2d, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x2f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x49, 0x44, 0x53, 0x1a, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b,
	0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x78, 0x12, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x78, 0x42, 0x69, 0x6e, 0x64, 0x1a, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x0b, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x41, 0x63, 0x63, 0x41, 0x64, 0x64, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x0a, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x0d, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63,
	0x63, 0x50, 0x77, 0x64, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x0e, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x55, 0x6e, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x32, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_acc_proto_rawDescOnce sync.Once
	file_proto_acc_proto_rawDescData = file_proto_acc_proto_rawDesc
)

func file_proto_acc_proto_rawDescGZIP() []byte {
	file_proto_acc_proto_rawDescOnce.Do(func() {
		file_proto_acc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_acc_proto_rawDescData)
	})
	return file_proto_acc_proto_rawDescData
}

var file_proto_acc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_acc_proto_goTypes = []interface{}{
	(*AEmpty)(nil),     // 0: proto.AEmpty
	(*Token)(nil),      // 1: proto.Token
	(*UUID)(nil),       // 2: proto.UUID
	(*UIDS)(nil),       // 3: proto.UIDS
	(*CreateTime)(nil), // 4: proto.CreateTime
	(*AccPwd)(nil),     // 5: proto.AccPwd
	(*Profile)(nil),    // 6: proto.Profile
	(*ProfSumm)(nil),   // 7: proto.ProfSumm
	(*ProfSumms)(nil),  // 8: proto.ProfSumms
	(*Contact)(nil),    // 9: proto.Contact
	(*RegStore)(nil),   // 10: proto.RegStore
	(*ProfStore)(nil),  // 11: proto.ProfStore
	(*ProfStores)(nil), // 12: proto.ProfStores
	(*RnStore)(nil),    // 13: proto.RnStore
	(*WxBind)(nil),     // 14: proto.WxBind
	(*Secures)(nil),    // 15: proto.Secures
	(*Admin)(nil),      // 16: proto.Admin
	(*Role)(nil),       // 17: proto.Role
	(*Result)(nil),     // 18: proto.Result
	(*UserRole)(nil),   // 19: proto.UserRole
	(*AddStore)(nil),   // 20: proto.AddStore
	(*RoleProf)(nil),   // 21: proto.RoleProf
	(*RoleProfs)(nil),  // 22: proto.RoleProfs
}
var file_proto_acc_proto_depIdxs = []int32{
	7,  // 0: proto.ProfSumms.summs:type_name -> proto.ProfSumm
	11, // 1: proto.ProfStores.profiles:type_name -> proto.ProfStore
	21, // 2: proto.RoleProfs.profiles:type_name -> proto.RoleProf
	1,  // 3: proto.Acc.ViaToken:input_type -> proto.Token
	17, // 4: proto.Acc.ViaRole:input_type -> proto.Role
	16, // 5: proto.Acc.ViaAdmin:input_type -> proto.Admin
	5,  // 6: proto.Acc.AccLogin:input_type -> proto.AccPwd
	2,  // 7: proto.Acc.GetProfile:input_type -> proto.UUID
	3,  // 8: proto.Acc.GetProfSumms:input_type -> proto.UIDS
	2,  // 9: proto.Acc.GetContact:input_type -> proto.UUID
	2,  // 10: proto.Acc.GetCreatetime:input_type -> proto.UUID
	19, // 11: proto.Acc.RoleProfiles:input_type -> proto.UserRole
	10, // 12: proto.Acc.StoreRegister:input_type -> proto.RegStore
	2,  // 13: proto.Acc.StoreProfile:input_type -> proto.UUID
	3,  // 14: proto.Acc.StoreProfiles:input_type -> proto.UIDS
	13, // 15: proto.Acc.StoreRename:input_type -> proto.RnStore
	14, // 16: proto.Acc.StoreBindWx:input_type -> proto.WxBind
	20, // 17: proto.Acc.StoreAccAdd:input_type -> proto.AddStore
	9,  // 18: proto.Acc.SetContact:input_type -> proto.Contact
	15, // 19: proto.Acc.BindAccount:input_type -> proto.Secures
	5,  // 20: proto.Acc.UnbindUnionID:input_type -> proto.AccPwd
	2,  // 21: proto.Acc.UnbindUnionID2:input_type -> proto.UUID
	5,  // 22: proto.Acc.ViaToken:output_type -> proto.AccPwd
	18, // 23: proto.Acc.ViaRole:output_type -> proto.Result
	0,  // 24: proto.Acc.ViaAdmin:output_type -> proto.AEmpty
	1,  // 25: proto.Acc.AccLogin:output_type -> proto.Token
	6,  // 26: proto.Acc.GetProfile:output_type -> proto.Profile
	8,  // 27: proto.Acc.GetProfSumms:output_type -> proto.ProfSumms
	9,  // 28: proto.Acc.GetContact:output_type -> proto.Contact
	4,  // 29: proto.Acc.GetCreatetime:output_type -> proto.CreateTime
	8,  // 30: proto.Acc.RoleProfiles:output_type -> proto.ProfSumms
	2,  // 31: proto.Acc.StoreRegister:output_type -> proto.UUID
	11, // 32: proto.Acc.StoreProfile:output_type -> proto.ProfStore
	12, // 33: proto.Acc.StoreProfiles:output_type -> proto.ProfStores
	0,  // 34: proto.Acc.StoreRename:output_type -> proto.AEmpty
	0,  // 35: proto.Acc.StoreBindWx:output_type -> proto.AEmpty
	0,  // 36: proto.Acc.StoreAccAdd:output_type -> proto.AEmpty
	0,  // 37: proto.Acc.SetContact:output_type -> proto.AEmpty
	1,  // 38: proto.Acc.BindAccount:output_type -> proto.Token
	0,  // 39: proto.Acc.UnbindUnionID:output_type -> proto.AEmpty
	0,  // 40: proto.Acc.UnbindUnionID2:output_type -> proto.AEmpty
	22, // [22:41] is the sub-list for method output_type
	3,  // [3:22] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_acc_proto_init() }
func file_proto_acc_proto_init() {
	if File_proto_acc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_acc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfSumm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfSumms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfStores); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RnStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxBind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Admin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleProf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleProfs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_acc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acc_proto_goTypes,
		DependencyIndexes: file_proto_acc_proto_depIdxs,
		MessageInfos:      file_proto_acc_proto_msgTypes,
	}.Build()
	File_proto_acc_proto = out.File
	file_proto_acc_proto_rawDesc = nil
	file_proto_acc_proto_goTypes = nil
	file_proto_acc_proto_depIdxs = nil
}
